# Site settings
title: Rachel McGrane | Designer from Pittsburgh
email: sayhi@rachelmcgrane.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rachel_mcgrane
github_username:  jekyll

sass:
  sass_dir: _sass
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
